<?php
/**
 * CLI: Export MySQL `barangay` schema+data as PostgreSQL SQL for pgAdmin 4.
 * Usage: php scripts/mysql_to_postgres_export.php [output.sql]
 */
if (PHP_SAPI !== 'cli') {
    http_response_code(403);
    exit("Forbidden\n");
}

require_once __DIR__ . '/../connection.php';

$outPath = $argv[1] ?? ('C:\\xampp\\secure\\backups\\barangay_postgres_' . date('Ymd_His') . '.sql');
$dbName = 'barangay';

$fh = fopen($outPath, 'wb');
if (!$fh) {
    fwrite(STDERR, "Cannot write $outPath\n");
    exit(1);
}

$w = static function (string $sql) use ($fh): void {
    fwrite($fh, $sql);
};

$w("-- PostgreSQL export of MySQL database `{$dbName}`\n");
$w("-- Generated: " . date('c') . "\n");
$w("-- Import in pgAdmin 4: Tools → Query Tool (or Restore/psql) after creating DB `{$dbName}`\n\n");
$w("SET client_encoding = 'UTF8';\n");
$w("SET standard_conforming_strings = on;\n\n");

$typeMap = static function (string $mysqlType, string $columnType): string {
    $t = strtolower($mysqlType);
    $ct = strtolower($columnType);
    if (str_contains($t, 'tinyint(1)') || $ct === 'tinyint(1)') {
        return 'smallint';
    }
    if (str_starts_with($t, 'tinyint') || str_starts_with($t, 'smallint')) {
        return 'smallint';
    }
    if (str_starts_with($t, 'mediumint') || str_starts_with($t, 'int')) {
        return 'integer';
    }
    if (str_starts_with($t, 'bigint')) {
        return 'bigint';
    }
    if (str_starts_with($t, 'decimal') || str_starts_with($t, 'numeric')) {
        if (preg_match('/decimal\((\d+),(\d+)\)/i', $ct, $m)) {
            return "numeric({$m[1]},{$m[2]})";
        }
        return 'numeric';
    }
    if (str_starts_with($t, 'float')) {
        return 'real';
    }
    if (str_starts_with($t, 'double')) {
        return 'double precision';
    }
    if (str_starts_with($t, 'datetime') || str_starts_with($t, 'timestamp')) {
        return 'timestamp';
    }
    if ($t === 'date') {
        return 'date';
    }
    if ($t === 'time') {
        return 'time';
    }
    if (str_starts_with($t, 'year')) {
        return 'smallint';
    }
    if (str_contains($t, 'blob') || str_contains($t, 'binary')) {
        return 'bytea';
    }
    if (str_contains($t, 'text') || str_contains($t, 'json')) {
        return 'text';
    }
    if (preg_match('/varchar\((\d+)\)/i', $ct, $m)) {
        return 'varchar(' . $m[1] . ')';
    }
    if (preg_match('/char\((\d+)\)/i', $ct, $m)) {
        return 'char(' . $m[1] . ')';
    }
    if (str_starts_with($t, 'enum') || str_starts_with($t, 'set')) {
        return 'text';
    }
    return 'text';
};

$qi = static function (string $ident): string {
    return '"' . str_replace('"', '""', $ident) . '"';
};

$lit = static function ($value) use ($con): string {
    if ($value === null) {
        return 'NULL';
    }
    if (is_int($value) || is_float($value)) {
        return (string) $value;
    }
    // bytea / binary as hex escape
    if (!mb_check_encoding((string) $value, 'UTF-8')) {
        return "'\\x" . bin2hex((string) $value) . "'::bytea";
    }
    $s = (string) $value;
    $s = str_replace(["\\", "'"], ["\\\\", "''"], $s);
    return "'" . $s . "'";
};

$tablesRes = $con->query(
    "SELECT TABLE_NAME
     FROM information_schema.TABLES
     WHERE TABLE_SCHEMA = DATABASE() AND TABLE_TYPE = 'BASE TABLE'
     ORDER BY TABLE_NAME"
);
$tables = [];
while ($row = $tablesRes->fetch_assoc()) {
    $tables[] = $row['TABLE_NAME'];
}

$w("BEGIN;\n\n");

foreach ($tables as $table) {
    $esc = $con->real_escape_string($table);
    $colsRes = $con->query(
        "SELECT COLUMN_NAME, DATA_TYPE, COLUMN_TYPE, IS_NULLABLE, COLUMN_DEFAULT, EXTRA, COLUMN_KEY
         FROM information_schema.COLUMNS
         WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = '{$esc}'
         ORDER BY ORDINAL_POSITION"
    );
    $cols = [];
    while ($c = $colsRes->fetch_assoc()) {
        $cols[] = $c;
    }

    $w("-- Table: {$table}\n");
    $w('DROP TABLE IF EXISTS ' . $qi($table) . " CASCADE;\n");
    $w('CREATE TABLE ' . $qi($table) . " (\n");

    $lines = [];
    $pk = [];
    foreach ($cols as $c) {
        $name = $c['COLUMN_NAME'];
        $pgType = $typeMap($c['DATA_TYPE'], $c['COLUMN_TYPE']);
        $extra = strtolower((string) $c['EXTRA']);
        if (str_contains($extra, 'auto_increment')) {
            if ($pgType === 'integer') {
                $pgType = 'integer GENERATED BY DEFAULT AS IDENTITY';
            } elseif ($pgType === 'bigint') {
                $pgType = 'bigint GENERATED BY DEFAULT AS IDENTITY';
            } else {
                $pgType = 'integer GENERATED BY DEFAULT AS IDENTITY';
            }
        }
        $null = strtoupper($c['IS_NULLABLE']) === 'YES' ? '' : ' NOT NULL';
        $default = '';
        $def = $c['COLUMN_DEFAULT'];
        if ($def !== null && !str_contains($extra, 'auto_increment')) {
            $defStr = (string) $def;
            if (strtoupper($defStr) === 'CURRENT_TIMESTAMP' || str_starts_with(strtoupper($defStr), 'CURRENT_TIMESTAMP')) {
                $default = ' DEFAULT CURRENT_TIMESTAMP';
            } elseif (preg_match('/^\'(.*)\'$/s', $defStr, $m)) {
                $default = ' DEFAULT ' . $lit($m[1]);
            } elseif (is_numeric($defStr)) {
                $default = ' DEFAULT ' . $defStr;
            } elseif (strtoupper($defStr) === 'NULL') {
                $default = ' DEFAULT NULL';
            } else {
                // MySQL expression defaults — skip unsafe ones
                $default = '';
            }
        }
        $lines[] = '  ' . $qi($name) . ' ' . $pgType . $null . $default;
        if ($c['COLUMN_KEY'] === 'PRI') {
            $pk[] = $qi($name);
        }
    }
    if ($pk !== []) {
        $lines[] = '  PRIMARY KEY (' . implode(', ', $pk) . ')';
    }
    $w(implode(",\n", $lines) . "\n);\n\n");
}

foreach ($tables as $table) {
    $qiTable = $qi($table);
    $result = $con->query('SELECT * FROM `' . $con->real_escape_string($table) . '`');
    if (!$result) {
        $w("-- skip data for {$table}: " . $con->error . "\n");
        continue;
    }
    $count = 0;
    while ($row = $result->fetch_assoc()) {
        if ($count === 0) {
            $colNames = array_map($qi, array_keys($row));
            $w('INSERT INTO ' . $qiTable . ' (' . implode(', ', $colNames) . ") VALUES\n");
        } else {
            $w(",\n");
        }
        $vals = [];
        foreach ($row as $v) {
            $vals[] = $lit($v);
        }
        $w('(' . implode(', ', $vals) . ')');
        $count++;
        if ($count % 200 === 0) {
            $w(";\n");
            $count = 0;
        }
    }
    if ($count > 0) {
        $w(";\n");
    }
    $w("\n");
}

$w("COMMIT;\n");
fclose($fh);

echo "Wrote PostgreSQL dump: {$outPath}\n";
echo 'Size: ' . filesize($outPath) . " bytes\n";
echo "Tables: " . count($tables) . "\n";
